server:
  port: 3344


spring:
  application:
    name: microserviecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SilenceIronMan/microservicecloud-config
